export const brandImages = [
    { id: 0, image: "1xbet.png" },
    { id: 1, image: "cbg.png" },
    { id: 2, image: "cocacola.png" },
    { id: 3, image: "danone.png" },
    { id: 4, image: "glovo.png" },
    { id: 5, image: "jumia.png" },
    { id: 6, image: "kellogs.png" },
    { id: 7, image: "mastercard.png" },
    { id: 8, image: "mtn.jpg" },
    { id: 9, image: "promasidor.png" },
    { id: 10, image: "shalina.png" },
    { id: 11, image: "societegeneral.png" },
    { id: 12, image: "unilever.png" },
    { id: 13, image: "1xbet.png" },
    { id: 14, image: "cbg.png" },
    { id: 15, image: "cocacola.png" },
    { id: 16, image: "danone.png" },
    { id: 17, image: "glovo.png" },
    { id: 18, image: "jumia.png" },
    { id: 19, image: "kellogs.png" },
    { id: 20, image: "mastercard.png" },
    { id: 21, image: "mtn.jpg" },
    { id: 22, image: "promasidor.png" },
    { id: 23, image: "shalina.png" },
    { id: 24, image: "societegeneral.png" },
    { id: 25, image: "unilever.png" },
    { id: 26, image: "usaembassy.png" },
    { id: 27, image: "usaid.png" },
    { id: 28, image: "voodoo.png" },
    { id: 29, image: "simplyblack.png" },
    { id: 30, image: "Princessetatie.png" },
    { id: 31, image: "Godrey.jpg" },
];

export const services = [
    {
        id: 0,
        heading: "Media Monitoring",
        list: [
            "Always-On Monitoring Platform",
            "AI-Enabled Real-time Reporting",
            "21 Countries",
            "1000+ Radio & TV Stations Monitored Daily",
        ],
        link: "/media-monitoring",
    },
    {
        id: 1,
        heading: "Audience Measurement",
        list: [
            "Ad Recall Measurements",
            "All Media and Product survey (AMPS)",
            "TV Audience Measurement (TAM)",
            "Radio Audience Measurement (RAM)",
        ],
        link: "/audience-measurement",
    },
    {
        id: 2,
        heading: "Consumer Journeys",
        list: [
            "Smart Survey",
            "(CAPI, CATI & CAWI)",
            "Brand Health Tracker (BHT)",
            "Usage and Attitude Studies",
        ],
        link: "/consumer-journeys",
    },
];

export const coverage = [
    { id: 0, country: "Benin", code: "bj" },
    { id: 1, country: "Burkina Faso", code: "bf" },
    { id: 2, country: "Cameroon", code: "cm" },
    { id: 3, country: "Chad", code: "td" },
    { id: 4, country: "Congo", code: "cd" },
    { id: 5, country: "Côte d'Ivoire", code: "ci" },
    { id: 6, country: "Gambia", code: "gm" },
    { id: 7, country: "Ghana", code: "gh" },
    { id: 8, country: "Guinea", code: "gn" },
    { id: 9, country: "Kenya", code: "ke" },
    { id: 10, country: "Madagascar", code: "mg" },
    { id: 11, country: "Mali", code: "ml" },
    { id: 12, country: "Mauritania", code: "mr" },
    { id: 13, country: "Niger", code: "ne" },
    { id: 14, country: "Nigeria", code: "ng" },
    { id: 15, country: "Senegal", code: "sn" },
    { id: 16, country: "Sierra Leone", code: "sl" },
    { id: 17, country: "Togo", code: "tg" },
    { id: 18, country: "Uganda", code: "ug" },
    { id: 19, country: "Zambia", code: "zm" },
];